# Generated by Django 4.2.7 on 2023-12-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(max_length=10, verbose_name="Subscription type"),
                ),
                (
                    "pricing_package",
                    models.CharField(max_length=20, verbose_name="Pricing package"),
                ),
                (
                    "card_number",
                    models.CharField(max_length=16, verbose_name="Card number"),
                ),
                (
                    "expiration_date",
                    models.CharField(max_length=5, verbose_name="Expiration date"),
                ),
                ("cvv", models.IntegerField(verbose_name="CVV")),
                ("start_date", models.DateField(verbose_name="Start date")),
                (
                    "finish_date",
                    models.DateField(blank=True, verbose_name="Finish date"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "website",
                    models.CharField(max_length=30, null=True, verbose_name="Website"),
                ),
                ("comment", models.CharField(max_length=255, verbose_name="Comment")),
                (
                    "date",
                    models.DateTimeField(auto_now=True, verbose_name="Published date"),
                ),
                (
                    "img",
                    models.ImageField(
                        default="images/anonymous_user_img.jpg",
                        upload_to="images",
                        verbose_name="User's image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="images", verbose_name="Image")),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
            ],
        ),
        migrations.CreateModel(
            name="FreeConsultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=30, verbose_name="Full name"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                ("topic", models.CharField(max_length=10, verbose_name="Topic")),
                ("message", models.TextField(verbose_name="Message")),
            ],
        ),
        migrations.CreateModel(
            name="LatestPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(upload_to="images", verbose_name="Post image"),
                ),
                ("title", models.CharField(max_length=30, verbose_name="Post title")),
                (
                    "content",
                    models.CharField(max_length=50, verbose_name="Post content"),
                ),
                (
                    "created_date",
                    models.DateField(auto_now=True, verbose_name="Post's created date"),
                ),
                (
                    "cat",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Category filter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Optional subject"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
            ],
        ),
        migrations.CreateModel(
            name="SubscribedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=30, unique=True, verbose_name="User email"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=30, verbose_name="Full name"),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("text", models.TextField(verbose_name="Text")),
                (
                    "img",
                    models.ImageField(
                        null=True, upload_to="images", verbose_name="Image"
                    ),
                ),
            ],
        ),
    ]
