# Generated by Django 4.2.7 on 2023-12-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="latestpost",
            name="cat",
            field=models.CharField(
                choices=[
                    ("News", ".filterNews"),
                    ("Business", ".filterBusiness"),
                    ("Technology", ".filterTechnology"),
                    ("Community", ".filterCommunity"),
                    ("Events", ".filterEvents"),
                    ("Other", ".filterOthers"),
                ],
                max_length=20,
                verbose_name="Category filter",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="images", verbose_name="Image"
            ),
        ),
    ]
