# Generated by Django 4.2.7 on 2023-12-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_latestpost_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="latestpost",
            name="cat",
            field=models.CharField(
                choices=[
                    ("filterNews", "News"),
                    ("filterBusiness", "Business"),
                    ("filterTechnology", "Technology"),
                    ("filterCommunity", "Community"),
                    ("filterEvents", "Events"),
                    ("filterOthers", "Other"),
                ],
                max_length=20,
                verbose_name="Category filter",
            ),
        ),
    ]
