# Generated by Django 4.2.7 on 2023-12-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_latestpost_cat"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="crete_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Created date and time"
            ),
        ),
    ]
