# Generated by Django 4.2.7 on 2023-12-07 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_comment_crete_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="crete_date",
        ),
    ]
