# Generated by Django 4.2.7 on 2023-12-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_remove_comment_crete_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Published date"
            ),
        ),
    ]
