# Generated by Django 4.2.7 on 2023-12-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_comment_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="img",
            field=models.ImageField(
                default="images/anonymous_user_img.jpg",
                upload_to="images",
                verbose_name="User's image",
            ),
        ),
    ]
