# Generated by Django 4.2.7 on 2023-12-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_comment_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="img",
            field=models.ImageField(
                default="images/anonymous_user_img.png",
                upload_to="images",
                verbose_name="User's image",
            ),
        ),
    ]
